### ISSUE TITLE
Reflection

### ISSUE THREAD

**Issue by ortolanph** [ortolanph/stringsplitter#1]
# Reflection

## Purpose of the backlog item
 
  * Implement splitters for float and double wrappers
  * Reorganize packages
  * Code Review

## Task list
 
   - [ ] **Studies**
     - [ ] Code
     - [ ] Article
     
  - [ ] EntityBuilder
     - [ ] Builder
     - [ ] Mechanics
  
  - [ ] **Other**
    - [ ] Reformat code
    - [ ] Code review
    - [ ] Update javadoc documentation
      - [ ] Calendar
      - [ ] Date
    - [ ] Update pacakge documentation
      - [ ] `primitives` package
    - [ ] Update main page
    - [ ] Write release notes
    - [ ] Merge with master
    - [ ] Create a JAR Release

**Comment by ortolanph** [comment]
Defined to be on the v5
