### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by ortolanph** [ortolanph/stringsplitter#2]
# Annotations

## Purpose of the backlog item

 * Studies on annotations and annotation processing. 
 * Annotations development
 * Annotations Processing development
 * Code Review

## Task list

- [ ] **Studies**
  - [ ] Code
  - [ ] Article

- [ ] **Annotations**
  - [ ] Test
  - [ ] Implementation
  - [ ] Commit changes

- [ ] **Annotations Processing**
  - [ ] Test
  - [ ] Implementation
  - [ ] Commit changes
 
 - [ ] **Other**
   - [ ] Reformat code
   - [ ] Code review
   - [ ] Update javadoc documentation
     - [ ] Calendar
     - [ ] Date
   - [ ] Update pacakge documentation
     - [ ] `primitives` package
   - [ ] Update main page
   - [ ] Write release notes
   - [ ] Merge with master
   - [ ] Create a JAR Release
