### ISSUE TITLE
Wiki pages

### ISSUE THREAD

**Issue by ortolanph** [ortolanph/stringsplitter#4]
# Wiki

## Purpose of the backlog item

 * Convert the README.md in a more detailed documentation

## Task list

- [ ] **Wiki**
  - [ ] Main page
  - [ ] Release Notes page
  - [ ] Technical Pages
    - [ ] String and String Array 
    - [ ] Wrappers 
    - [ ] Dates 
  - [ ] Next Versions Page

**Comment by ortolanph** [comment]
Defined to be on the v5 version
